use nxsetings db now

diff --git a/nxkeygen b/nxkeygen
--- a/nxkeygen
+++ b/nxkeygen
@@ -16,7 +16,12 @@
 # ========================================================================
 
 # Read the config file
-. $(PATH=$(cd $(dirname $0) && pwd):$PATH which nxloadconfig) --
+SHARED_CONFS="/usr/share/freenx-server"
+. $SHARED_CONFS/nxfuncs
+open_dbe $$
+attach_db "$sq_settings_fn" ro || {
+	echo "Unable to attach db file $sq_settings_fn"; exit 1;
+}
 
 [ -z "$NX_KEY_DIR" ] && NX_KEY_DIR="$NX_HOME_DIR/.ssh"
 DATE="`date '+%Y%m%d-%H%M%S'`"
@@ -75,3 +80,5 @@ if [ -f "${NX_SERVER_KEY}" -a -f "${NX_CLIENT_KEY}" -a \
 fi
 
 main "$@"
+
+close_dbe $$
diff --git a/nxnode b/nxnode
--- a/nxnode
+++ b/nxnode
@@ -7,10 +7,7 @@
 
 shopt -s extglob
 
-# Read the config file
-# dimbor: it's temporary
-. /usr/bin/nxloadconfig --userconf
-
+SHARED_CONFS="/usr/share/freenx-server"
 . $SHARED_CONFS/nxfuncs
 #
 # -----------------------------------------------------------------------------
@@ -185,7 +182,7 @@ uservice_configure() {
 		optstr="uid=$USER,gid=$egroup,ip=127.0.0.1,port=$3,username=$4"
 		[ -n "$5" ] && optstr+=",password=$5"
 		[ -n "$SMB_MOUNT_OPTIONS" ] && optstr+=",$SMB_MOUNT_OPTIONS"
-		cmdstr="$COMMAND_SMBMOUNT $2 $6 -o $optstr"
+		cmdstr="$COMMAND_SUDO $COMMAND_SMBMOUNT $2 $6 -o $optstr"
 		echo "$cmdstr"
 	;;
 	smb-prn|ipp-prn)
@@ -215,7 +212,7 @@ uservice_configure() {
 		[ "${1:0:3}" = "smb" ] && \
 			uri="nxsmb://$4:$5@127.0.0.1:$3/cifs/$8" || \
 			uri="ipp://$4:$5@127.0.0.1:$3/printers/$8"
-		cmdstr="$COMMAND_LPADMIN -p $svc -P $ppdfn -v $uri -E"
+		cmdstr="$COMMAND_SUDO $COMMAND_LPADMIN -p $svc -P $ppdfn -v $uri -E"
 		echo "$cmdstr"
 	;;
 	media-pa)
@@ -275,12 +272,12 @@ uservice_mount() {
 		# post-configure
 		local public=$(getparam "$6" "public" "" ';')
 		[ "$public" != "1" ] && {
-		errstr=$($COMMAND_LPADMIN -p $svc -u allow:$USER,guest,root 2>&1) || \
+		errstr=$($COMMAND_SUDO $COMMAND_LPADMIN -p $svc -u allow:$USER,guest,root 2>&1) || \
 			{ nxlog "$lp $2 ($3) printer set permission failed: $errstr"; }
 		}
 		local defp=$(getparam "$6" "defaultprinter" "" ';')
 		[ "$defp" = "1" ] && {
-		errstr=$($COMMAND_LPADMIN -d $svc 2>&1) || \
+		errstr=$($COMMAND_SUDO $COMMAND_LPADMIN -d $svc 2>&1) || \
 			{ nxlog "$lp $2 ($3) printer set to default failed: $errstr"; }
 		}
 		nxlog "$lp $2 ($3) printer installed"
@@ -361,7 +358,7 @@ uservice_umount() {
 		#}
 		for (( i=1; i<=ct; i++ )); do
 			(( i>=ct/2 )) && ffl="-f"
-			errstr+=$($COMMAND_SMBUMOUNT $ffl "$res" 2>&1) && \
+			errstr+=$($COMMAND_SUDO $COMMAND_SMBUMOUNT $ffl "$res" 2>&1) && \
 				{ ok="1"; break; }
 			sleep $step"s"
 		done
@@ -372,7 +369,7 @@ uservice_umount() {
 	;;
 	smb-prn|ipp-prn)
 		for (( i=1; i<=ct; i++ )); do
-			errstr+=$($COMMAND_LPADMIN -x "$2" 2>&1) && \
+			errstr+=$($COMMAND_SUDO $COMMAND_LPADMIN -x "$2" 2>&1) && \
 				{ ok="1"; break; }
 			sleep $step"s"
 		done
@@ -1193,8 +1190,8 @@ startsession() { # Start a new session.
 
 	[ "$1" = "start" ] && mkdir -p -m700 "$NXSESSION_DIRECTORY"
 	# Setup environment
-	[ -n "$SOURCE_SYS_PROFILE" ] && . "$SOURCE_SYS_PROFILE"
-	[ -n "$SOURCE_USER_PROFILE" ] && . "$SOURCE_USER_PROFILE"
+	[ -n "$SOURCE_SYS_PROFILE" ] && . $SOURCE_SYS_PROFILE
+	[ -n "$SOURCE_USER_PROFILE" ] && . ${SOURCE_USER_PROFILE@P}
 
 	[ "$PROXY_TCP_NODELAY" = "0" ] && nodelay=0
 	[ "$ENABLE_ROOTLESS_MODE" = "0" ] && rootless=0
@@ -1366,6 +1363,11 @@ cmd_node_suspend() {
 # -----------------------------------------------------------------------------
 declare -g delim="NX>" CMDLINE="" nx_dir nxuser_logfile umask0=$(umask);
 open_dbe $$
+attach_db "$sq_settings_fn" ro || {
+	echo "$delim 500 Error: NXNODE: Unable to attach db file $sq_settings_fn";
+	exit_proc 1;
+}
+set_vars_from_db "" $USER
 
 [ -n "$2" ] && delim="NX-$2>"
 echo "$delim 1000 NXNODE - Version $NX_VERSION $NX_LICENSE"
diff --git a/nxserver b/nxserver
--- a/nxserver
+++ b/nxserver
@@ -17,10 +17,7 @@
 
 shopt -s extglob
 
-# Read the config file
-# dimbor: it's temporary
-. /usr/bin/nxloadconfig --userconf
-
+SHARED_CONFS="/usr/share/freenx-server"
 . $SHARED_CONFS/nxfuncs
 
 log() {
@@ -72,7 +69,6 @@ echo_x() { log "$@"; echo "$@"; }
 
 # =================== sqlite3 stuff =====================
 
-sess_bd="$NX_SESS_DIR/sessions.sq3"
 sqcols_sess="session_id, session, display, status, userip,\
  rootless, type, user, screeninfo, geometry, host, shadowcookie,\
  startTime, creationTime, endTime"
@@ -380,7 +376,6 @@ session_fail() {
 # NX_ETC_DIR NX_HOME_DIR NX_LICENSE NX_LOGFILE NX_LOG_LEVEL
 # NX_SESS_DIR NX_VERSION
 # SERVER_NAME SESSION_HISTORY SESSION_LIMIT SESSION_USER_LIMIT
-# SHARED_CONFS
 
 # declare global variables:
 declare -g cmd in_params proto login_success login_method
@@ -393,7 +388,14 @@ server_mode="0"; [ "$USER" = "nx" ] && server_mode="1"
 if [ "$server_mode" = "1" ]; then
 
 # Start!
-open_dbe $$ && attach_db $sess_bd && init_sess_db
+open_dbe $$
+attach_db "$sq_settings_fn" ro || {
+	echo "NX> 500 Error: Unable to attach db file $sq_settings_fn";
+	exit_proc 1;
+}
+set_vars_from_db
+sess_bd="$NX_SESS_DIR/sessions.sq3"
+attach_db $sess_bd && init_sess_db
 
 log "-- NX SERVER START: $@ - ORIG_COMMAND=$SSH_ORIGINAL_COMMAND"
 
@@ -443,14 +445,13 @@ preferred_host=$(rematchfn "host=([^&]*)" "$SSH_ORIGINAL_COMMAND") #"
 				if [ "$login_success" = "0" ]; then
 					log -n "su "
 					LANG=C echo "$PASS" | \
-						/usr/bin/sudo -u $user -Svk -p "" >/dev/null 2>&1
+						$COMMAND_SUDO -u $user -Svk -p "" >/dev/null 2>&1
 					if [ $? -eq 0 ]; then login_success="1"; login_method="SU"; fi
 				fi
 
 				if [ "$login_success" = "1" ]; then
 					# Reread the config files (so that $USER.node.conf get sourced)
-					# dimbor: it's temporary
-					# . /usr/bin/nxloadconfig --userconf
+					set_vars_from_db "" $user "only"
 					break
 				else
 					echo_x "NX> 404 ERROR: wrong password or login"
@@ -499,7 +500,7 @@ server_nxnode_start() {
 	NODE_HOSTNAME=$host; [ -z "$NODE_HOSTNAME" ] && NODE_HOSTNAME="127.0.0.1"
 	export NODE_HOSTNAME
 	echo -e "$PASS\n$@" | \
-		/usr/bin/sudo -u $user -HSik -p "" $PATH_BIN/nxnode "$cmd" 2>&1 | \
+		$COMMAND_SUDO -u $user -HSik -p "" $PATH_BIN/nxnode "$cmd" 2>&1 | \
 			log_tee
 }
 
@@ -1358,15 +1359,21 @@ cmd_terminate_or_send() {
 	done <<< "$cmd_params"
 }
 
+open_dbe $$
+attach_db "$sq_settings_fn" ro || {
+	echo "NX> 500 Error: Unable to attach db file $sq_settings_fn";
+	exit_proc 1;
+}
+set_vars_from_db
+sess_bd="$NX_SESS_DIR/sessions.sq3"
 if [ "$NX_LOG_LEVEL" != "0" -a ! -f "$NX_LOGFILE" ]; then
 	touch "$NX_LOGFILE" >/dev/null 2>&1
 fi
-open_dbe $$ && attach_db $sess_bd && init_sess_db
 if [ "$UID" -eq "0" ]; then
 	chown nx "$NX_LOGFILE" >/dev/null 2>&1; chmod 660 "$NX_LOGFILE"
 	chown nx "$sess_bd" >/dev/null 2>&1; chmod 660 "$sess_bd"
 fi
-
+attach_db $sess_bd && init_sess_db
 #
 # normal user available functions
 if [ $UID -ne 0 ]; then
