Initial support for guests sessions

diff --git a/nxserver b/nxserver
--- a/nxserver
+++ b/nxserver
@@ -796,6 +796,28 @@ do
 
 			USER=$USER2
 
+			# Guest authentication
+			if [ "$USER" = "NX guest user" ]
+			then
+				if [ "$ENABLE_GUEST_LOGIN" != "1" ]
+				then
+					echo_x "NX> 404 ERROR: guest authentication not enabled"
+					echo_x "NX> 999 Bye"
+					if [ "$ENABLE_LOG_FAILED_LOGINS" = "1" ]
+					then
+						logger -t nxserver -i -p auth.info "($(whoami)) Failed login for user=$USER from IP=$(echo $SSH_CLIENT | awk '{print $1}')"
+					fi
+					exit 1
+				fi
+				log 6 -n "guest "
+				nxnode_login "" -- guest "" "" "$COMMAND_GUEST_LOGIN" --check 2>&1 >/dev/null
+                                if [ $? -eq 0 ]
+                                then
+                                        LOGIN_SUCCESS="1"
+                                        LOGIN_METHOD="GUEST"
+                                fi
+			fi
+
 			# PASSDB based auth
 			if [ "$ENABLE_PASSDB_AUTHENTICATION" = "1" -a "$LOGIN_SUCCESS" = "0" ]
 			then
@@ -916,7 +938,10 @@ server_nxnode_start()
 	export NODE_HOSTNAME
 	
 	# Use nxnode-login?
-	if [ "$LOGIN_METHOD" = "SSH" ]
+	if [ "$LOGIN_METHOD" = "GUEST" ]
+        then
+            NXNODE_TOSEND="$@" nxnode_login "" -- guest "" "" "$COMMAND_GUEST_LOGIN" "$CMD" 2>&1 | log_tee
+        elif [ "$LOGIN_METHOD" = "SSH" ]
 	then
 	    export COMMAND_SSH
 	    NXNODE_TOSEND="$@" nxnode_login "$PASS" -- ssh "$USER" "$SSHD_PORT" "$PATH_BIN/nxnode" "$CMD" 2>&1 | log_tee
@@ -1263,6 +1288,7 @@ server_startrestore_session()
 	server_get_params $CMD
 	PARAMS=$SERVER_PARAMS
 	PARAMS="$PARAMS&clientproto=$PROTO"
+	PARAMS="$PARAMS&login_method=$LOGIN_METHOD"
 	CMDLINE=$PARAMS
 	echo_x
 
