implementation of GUEST_LOGIN Add new variable COMMAND_NXSHADOWACL,COMMAND_NXACL,COMMAND_NXCHECKLOAD,COMMAND_NXAGENT

diff --git a/freenx-server/nxserver b/freenx-server/nxserver
--- a/freenx-server/nxserver
+++ b/freenx-server/nxserver
@@ -295,9 +295,9 @@ session_list_user_suspended()
 				then 
 					[ -z "$(getparam shadowcookie)" ] && continue
 					
-					if [ -x "$PATH_BIN/nxshadowacl" ]
+					if [ -x "$COMMAND_NXSHADOWACL" ]
 					then
-						$PATH_BIN/nxshadowacl "$(getparam userName)" "$USER" || continue
+						$COMMAND_NXSHADOWACL "$(getparam userName)" "$USER" || continue
 					fi
 				fi
 			fi
@@ -796,6 +796,33 @@ do
 
 			USER=$USER2
 
+			# Guest authentication
+			if [ "$USER" = "NX guest user" ]
+			then
+				if [ "$ENABLE_GUEST_LOGIN" != "1" -o ! -x "$COMMAND_GUEST_LOGIN" ]
+				then
+					if [ "$ENABLE_GUEST_LOGIN" != "1" ]
+					then
+						echo_x "NX> 404 ERROR: guest authentication not enabled"
+					else
+						echo_x "NX> 404 ERROR: $COMMAND_GUEST_LOGIN not correct"
+					fi
+					echo_x "NX> 999 Bye"
+					if [ "$ENABLE_LOG_FAILED_LOGINS" = "1" ]
+					then
+						logger -t nxserver -i -p auth.info "($(whoami)) Failed login for user=$USER from IP=$(echo $SSH_CLIENT | awk '{print $1}')"
+					fi
+					exit 1
+				fi
+				log 6 -n "guest "
+				nxnode_login "" -- guest "" "" "$COMMAND_GUEST_LOGIN" --check 2>&1 >/dev/null
+                                if [ $? -eq 0 ]
+                                then
+                                        LOGIN_SUCCESS="1"
+                                        LOGIN_METHOD="GUEST"
+                                fi
+			fi
+
 			# PASSDB based auth
 			if [ "$ENABLE_PASSDB_AUTHENTICATION" = "1" -a "$LOGIN_SUCCESS" = "0" ]
 			then
@@ -916,7 +943,10 @@ server_nxnode_start()
 	export NODE_HOSTNAME
 	
 	# Use nxnode-login?
-	if [ "$LOGIN_METHOD" = "SSH" ]
+	if [ "$LOGIN_METHOD" = "GUEST" ]
+        then
+            NXNODE_TOSEND="$@" nxnode_login "" -- guest "" "" "$COMMAND_GUEST_LOGIN" "$CMD" 2>&1 | log_tee
+        elif [ "$LOGIN_METHOD" = "SSH" ]
 	then
 	    export COMMAND_SSH
 	    NXNODE_TOSEND="$@" nxnode_login "$PASS" -- ssh "$USER" "$SSHD_PORT" "$PATH_BIN/nxnode" "$CMD" 2>&1 | log_tee
@@ -987,10 +1017,10 @@ server_nxnode_start_wait()
 	do
 		case "$CMD" in 
 			"NX> 706"*)
-				if [ -x "$PATH_BIN/nxshadowacl" ]
+				if [ -x "$COMMAND_NXSHADOWACL" ]
 				then
 					# check if we should save the cookie
-					$PATH_BIN/nxshadowacl "$USER"
+					$COMMAND_NXSHADOWACL "$USER"
 					
 					if [ $? -eq 0 ]
 					then
@@ -1074,10 +1104,10 @@ server_nxnode_start_wait()
 	do
 		case "$CMD" in 
 			"NX> 706"*)
-				if [ -x "$PATH_BIN/nxshadowacl" ]
+				if [ -x "$COMMAND_NXSHADOWACL" ]
 				then
 					# check if we should save the cookie
-					$PATH_BIN/nxshadowacl "$USER"
+					$COMMAND_NXSHADOWACL "$USER"
 					
 					if [ $? -eq 0 ]
 					then
@@ -1211,7 +1241,7 @@ server_loadbalance_load()
 	
 	for i in $LOAD_BALANCE_SERVERS
 	do
-		SERVER_LB_LOAD=$($NX_DIR/bin/nxcheckload $i)
+		SERVER_LB_LOAD=$($COMMAND_NXCHECKLOAD $i)
 		[ -z "$SERVER_LB_LOAD" ] && continue
 		
 		if [ $SERVER_LB_LOAD -gt $SERVER_LB_MAX ]
@@ -1263,6 +1293,7 @@ server_startrestore_session()
 	server_get_params $CMD
 	PARAMS=$SERVER_PARAMS
 	PARAMS="$PARAMS&clientproto=$PROTO"
+	PARAMS="$PARAMS&login_method=$LOGIN_METHOD"
 	CMDLINE=$PARAMS
 	echo_x
 
@@ -1344,8 +1375,7 @@ server_startrestore_session()
 		if [ "$ENABLE_EXTERNAL_NXDESKTOP" = "1" -a "$(getparam type)" = "windows" ]
 		then
 			type="windows-helper"
-			application="$PATH_BIN/nxdesktop_helper"
-			PARAMS="$PARAMS&type=$type&application=$application&freenx_export_agents=1"
+			PARAMS="$PARAMS&type=$type&freenx_export_agents=1"
 			CMDLINE=$PARAMS
 		fi
 		 
@@ -1381,10 +1411,10 @@ server_startrestore_session()
 			return 1
 	fi
 
-	if [ -x "$PATH_BIN/nxacl" ]
+	if [ -x "$COMMAND_NXACL" ]
 	then
-			log 3 "Info: Using $PATH_BIN/nxacl to change session parameters or deny session."
-			NEW_PARAMS=$($PATH_BIN/nxacl "$CMDLINE")
+			log 3 "Info: Using $COMMAND_NXACL to change session parameters or deny session."
+			NEW_PARAMS=$($COMMAND_NXACL "$CMDLINE")
 			if [ $? -ne 0 ]
 			then
 				echo_x "NX> 596 The session failed due to a nxacl policy setting: $NEW_PARAMS"
